Финальный этап
htmlacademy-adaptive/1903913-sedona-24 pull request #7
Opened 2022-01-07 11:34 UTC by Aurin97

2022-01-15 19:49 UTC, Zotova2008 commented on source/sass/blocks/form.scss
> +.form__label-3 {
```
.form__list-2 .form__item {
    margin-bottom: 28px;
}
```

2022-01-15 19:49 UTC, Zotova2008 commented on source/sass/blocks/form.scss
> +  @media (min-width: 768px) {
```
.form__list {
  @media (min-width: 768px) {
      padding-top: 46px;
      padding-left: 10px;
  }
  ```

2022-01-15 19:49 UTC, Zotova2008 commented on source/sass/blocks/form.scss
> +    grid-column: 1/2;
Всей форме начиная с планшета добавить горизонтальные паддинги по 60px

2022-01-15 19:49 UTC, Zotova2008 commented on source/catalog.html
>          <div class="mountains__bg-2">
Не доделаны характеристики текстов для планшета и декстопа.

2022-01-17 14:42 UTC, Zotova2008 commented on source/form.html
> +                 <span class="form__icon-tel"></span>
- [ ] Иконки телефона и электронной почты прописать с модификатором. Ты стили скопировал, но не подумал для чего они 
```
<span class="form__icon form__icon--tel"></span>
<span class="form__icon form__icon--email"></span>
```

- [ ] `.form__input-container` прописать `position: absolute`
- [ ] `.form__input-text` убрать левый маргин и отодвигать блоки с помощью паддинга на fieldset

2022-01-17 14:42 UTC, Zotova2008 commented on source/sass/blocks/form.scss
Не сделано
```
.form__label {
    display: block;
    position: relative;
    padding: 15px 10px 10px 78px;
}
```

2022-01-17 14:42 UTC, Zotova2008 commented on source/form.html
>          <form class="form" action="https://echo.htmlacademy.ru/" method="get">
Не сделано
- [ ] Всей форме начиная с планшета добавить горизонтальные паддинги по 60px
- [ ] Не доделаны характеристики текстов для планшета и декстопа.
- [ ] Проверить еще раз по макету
- [ ] есть ошибки на главной в валидаторе https://validator.w3.org/nu/#textarea

2022-01-18 18:52 UTC, Zotova2008 commented on source/form.html
>                <div class="form__input-container">
Заголовок на странице каталога на планшете не соответствует макету http://joxi.ru/Q2K8okvtOK6nEA http://joxi.ru/EA4Dx0VUX75b0A, http://joxi.ru/gmvQNMKseOGpvr
на десктопе http://joxi.ru/82QGlJvi8nNjQr

Заголовок на странице формы на планшете и десктопе не соответствует макету http://joxi.ru/8Angn1jHN3Enxr http://joxi.ru/Y2LNo1vcxZYbWr

Не сделаны полосочки у заголовков внутри fieldset http://joxi.ru/krDnoawUGa9W32 http://joxi.ru/8Angn1jHN3Ewbr

2022-01-18 18:52 UTC, Zotova2008 commented on source/form.html
>                <div class="form__input-container">
Блок с видео абзац текст "смотрите видеопрезентацию ..." не по макету.
В макете на планшете http://joxi.ru/brR0oqvTBXRwe2, а у тебя http://joxi.ru/krDnoawUGa90y2
На десктопе http://joxi.ru/12MJoyvTgaWlQA

2022-01-18 18:52 UTC, Zotova2008 commented on source/form.html
>                <div class="form__input-container">
Зачем заголовку `.form__lagend-4` задавать центровку и отрицательный маргин? Не прописывай центровку тогда http://joxi.ru/ZrJ7oxvUQLynPm

2022-01-18 18:52 UTC, Zotova2008 commented on source/form.html
> -                 <input class="form__input-text" type="text" name="text-telephone" id="text-telephone" placeholder="Введите телефон">
По макету кнопка "Отправить отзыв" заглавными буквами - у тебя нет http://joxi.ru/8Angn1jHN3EoOr

2022-01-18 18:52 UTC, Zotova2008 commented on source/sass/blocks/form.scss
> +.form__input-container {
Обвертке input и иконке `.form__input-container` Нужно задать не absolute (нам же не нужно вырвать из потока этот блок), а ralative (что бы иконка позиционировалась относительно обвертки `.form__input-container`)

У инпутов телефона и почты убрать левый маргин http://joxi.ru/l2ZWozptlJYk0A
У иконок top и right всегда будет 0 http://joxi.ru/v2958bVs4xDN62 http://joxi.ru/zANqo7vH1RaVn2

2022-01-18 18:52 UTC, Zotova2008 commented on source/form.html
>                 <label class="form__label-text" for="text-telephone">Контактный телефон<sup>*</sup>:</label>
Главная не по макету
- [ ] мобильная http://joxi.ru/v2958bVs4xKlz2 http://joxi.ru/zANqo7vH1RLzD2
- [ ] планшет http://joxi.ru/Q2K8okvtOK6E6A
- [ ] десктоп http://joxi.ru/823DXGVUzvQlyA http://joxi.ru/l2ZWozptlJyQ4A http://joxi.ru/LmGkoOvUB6NzYm

Каталог не по макету
- [ ] мобильный http://joxi.ru/1A5DkEVU4d6Ra2 http://joxi.ru/LmGkoOvUB6NNYm http://joxi.ru/D2PMoNvtwOZD0A
- [ ] планшет http://joxi.ru/vAWQoEjs3wxpqm http://joxi.ru/vAWQoEjs3wzkPm http://joxi.ru/a2X5ojvsQ89ynA
- [ ] десктоп http://joxi.ru/EA4Dx0VUX7kwVA http://joxi.ru/82QGlJvi8nNjQr http://joxi.ru/v2958bVs4xDZv2

Форма
- [ ] мобильный http://joxi.ru/brR0oqvTBXGY12
- [ ] Для планшета и десктопа тоже не по макету

2022-01-18 18:52 UTC, Zotova2008 commented on source/form.html
> -                 <input class="form__input-text" type="text" name="text-telephone" id="text-telephone" placeholder="Введите телефон">
Не сделано: Есть ошибки на главной в валидаторе https://validator.w3.org/nu/#textarea

2022-01-27 11:33 UTC, vlad-donchenko requested changes

2022-01-27 11:33 UTC, vlad-donchenko commented on source/form.html
> +            <label class="form__label2" for="text-middle-name">Отчество<sup>*</sup>:
Основная проблема которую надо сейчас решить это соответствие макету.

**Главная (моб. версия)**

- [ ] Изменить высоту .mountains__bg изменить `min-height: 389px` на `min-height: 333px `http://joxi.ru/ZrJaZQqcbpgP9A 
Почему 333px? Высота header `56px`, header и .mountains__bg `389px`, отнимаешь высоту header от .mountains__bg и получаешь `333px`, а это то что нужно http://joxi.ru/zANnOd5U8DgkXA

- [ ]  .mountains__bg  `padding-top: 34px` http://joxi.ru/n2YQqezS7xONp2. Почему 34px? Отступ от header к картинке в  .mountains__bg

- [ ] .mountains__place - изменить размер шрифта c `30px` на `18px`, добавить `text-transform: uppercase;` margin-bottom: 30px; .mountains__reasons  `font-size: 18px`.
Во вкладке inspect http://joxi.ru/Rmz0L9gcjyN0QA, http://joxi.ru/Rmz0L9gcjyN0QA - есть все размеры, все размеры в текстах нужно сравнить с макетом и изменить где нужно!

**Фото и видео (моб. версия)**

- [ ] .mountains__bg-2  `min-height: 158px`, по аналогии с .mountains__bg, посчитал размер!
- [ ] Размер шрифта должен быть `18px` http://joxi.ru/MAjyx3MH15KGq2. Внутри блока .mountains__content-3 - подбери макетные отступы.

Форма отзыва (моб. версия)

После правок над  .mountains__bg-2 и .mountains__place, у тебя все станет на места!

2022-01-28 00:23 UTC, vlad-donchenko commented on source/sass/blocks/videocontent.scss
Главная (моб)
- [ ]  .mountains__bg (http://joxi.ru/823aR9jcaWkXMr).
- [ ] .mountains__content (http://joxi.ru/BA0LK94TvWaN3A, http://joxi.ru/KAxvWn5tvke6Qm)
- [ ] .mountains__reasons (http://joxi.ru/p27nXWLUnBRDdm)
- [ ] .advantages__item-list--mask (http://joxi.ru/n2YQqezS7x9nG2)

Фото и Видео (моб)
- [ ] .mountains__content-3 (http://joxi.ru/J2bRK65igZJBG2, http://joxi.ru/bmoq8xOc7KLk7A, http://joxi.ru/V2VN8DeC834MG2).
- [ ] .photogallery (http://joxi.ru/Drl81vOtGPR5Qr)
- [ ] .photogallery__list , должны быть только .photogallery__item, без photogallery__item-2 итд!
- [ ] Картинки должны быть 280, а у тебя одна 260, нужно исправить http://joxi.ru/4Ak7kyOF069bwA.

Форма (моб)
- [ ] .mountains__content-2 (http://joxi.ru/V2VN8DeC834NG2, http://joxi.ru/xAenRLeUbj1L7r, http://joxi.ru/Drl81vOtGPReQr).

2022-01-29 19:56 UTC, vlad-donchenko commented on source/form.html
>                </li>
http://joxi.ru/KAgxOZMcNvzNvr - Присмотрись к этой секции, у тебя есть 5 блоков. 3 серого цвета, 1 синий, а второй картинка. Картинке и блоку синего цвета нужно дать модификатор. Для остальных определить базовые стили в .advantages__item-list который нужно переименовать на .advantages__item - задать макетные padding-left, padding-right! .advantages__container (`1px solid #d6d6d6`); .

Итог
http://joxi.ru/5mdOadWhaXRJWr - Здесь нам нужны отступ слева и справа чтобы линия с низу не прилипла к краям.
http://joxi.ru/823aR9jcaWNwWr - Здесь нам нужно чтобы был отступ от линии.

http://joxi.ru/L21KZ9jUz47Der - Такого быть не должно, margin в текстовых узлах ты определяешь четко, руками, в блоках ты убираешь margint-top и пишешь margin-bottom! Отступа сверху делаешь через padding!

2022-01-29 20:16 UTC, vlad-donchenko requested changes

2022-01-29 20:16 UTC, vlad-donchenko commented on source/form.html
>                  <label class="form__label" for="impressions2">
- [ ] http://joxi.ru/8AnJ7x0UolZnkA - То что есть, то что должно быть - http://joxi.ru/823aR9jcaWN5Or! (Допиши себе стили которые я выделил).
- [ ] http://joxi.ru/v29xkLJcR60L0m - То что есть, то что должно быть -http://joxi.ru/Rmz0L9gcjy9O8A.
- [ ] http://joxi.ru/DmBQMlESgbV5gr http://joxi.ru/82QkxZ7IVOQ64r - Привести все блоки в такой вид. У текстовых элементов обнулить отступы сверху, отступы у нас только снизу и у последнего элемента обнулены! Это сделать по всем страницам!

2022-02-02 18:28 UTC, merged